baseurl = "https://datafibers-community.github.io/"
title = "DataFibers"
theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "sparkera"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-40213017-3"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
	
[[menu.main]]
    name = "Download"
    url  = "http://github.com/datafibers-community/df_data_service/releases/latest"
    weight = 2

[[menu.main]]
    name = "Community"
    identifier = "community"
    url  = "/community/"
    weight = 3
	
[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 4

[[menu.main]]
    name = "Training"
    url  = "/training/"
    weight = 5	

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/datafibers-community/"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:datafibers@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DataFibers"
    defaultKeywords = ["datafibers", "big data", "streaming"]
    defaultDescription = "DataFibers enterprise open source data bus"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCksU3IZTuUK6fA-doQUfQ4KcYm7mB_vlk"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "datafibers@gmail.com"

    about_us = "<p>DataFibers are expertises by applying its cutting edge big data technologies and solutions on enterprise big data centric use cases.</p>"
    copyright = "Copyright (c) 2020, DataFibers all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>DataFibers.</strong>
        <br>7030 Woodbine Avenue,
        <br>L3R 6G2
        <br>Ontario, Markham
        <br>Canadar
        <br>
        <br>
        <strong>Tel: +1 (647) 960-8578</strong>
        <br>
      """
    latitude = "43.814335"
    longitude = "-79.350649"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us at datafibers@gmail.com</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "Our communities have worked with many companies, technical groups, and big data funs and we always like to hear their feedbacks. Have a look at what they talks about DataFibers."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Know more about DataFibers?"
    subtitle = "Check out <<DataFibers Complete Guideline>>"
    link_url = "https://datafibers-community.gitbooks.io/datafibers-complete-guide/content/"
    link_text = "Read Our EBook"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Technologies"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Here, we are sharing our experience and best practice of using DataFibers as well as other big data technology."
